# Generated by Django 4.2.3 on 2023-11-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
