# Generated by Django 4.2.7 on 2023-11-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_city_listing_street'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing_rent',
        ),
    ]
