# Generated by Django 4.2.7 on 2023-11-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_delete_listing_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='street',
        ),
    ]
