# Generated by Django 4.2.7 on 2023-11-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_listing_state_remove_listing_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
    ]
